repos:
  - repo: https://github.com/valeratrades/cargo-sort
    rev: v0.1.1
    hooks:
    - id: cargo-sort-workspace-grouped
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: trailing-whitespace
    - id: check-yaml
