name: +r Merge

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-and-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check last comment for +r
      id: check_comment
      uses: actions/github-script@v6
      with:
        script: |
          const { data: comments } = await github.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          const lastComment = comments[comments.length - 1];
          return lastComment.body.trim() === '+r';

    - name: Get the status of the last workflow run
      id: check_workflow
      uses: actions/github-script@v6
      with:
        script: |
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const branch = context.payload.pull_request.head.ref;

          const runs = await github.actions.listWorkflowRunsForRepo({
            owner,
            repo,
            branch,
            per_page: 1,
            status: 'success',
          });

          if (runs.data.workflow_runs.length > 0) {
            return runs.data.workflow_runs[0].status === 'completed';
          } else {
            return false;
          }

    - name: Set up Git credentials
      if: steps.check_comment.outputs.result == 'true' && steps.check_workflow.outputs.result == 'true'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Merge to master
      if: steps.check_comment.outputs.result == 'true' && steps.check_workflow.outputs.result == 'true'
      run: |
        git checkout master
        git merge ${{ github.head_ref }}
        git push origin master

